# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='Email',
            field=models.CharField(default='example@counsel.com', max_length=50),
        ),
    ]
