# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT', '0005_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='new',
        ),
    ]
